def extract_countries(text):
    ltext = text.lower()
    c = []
    for country, patterns in COUNTRY_MAP.items():
        for pattern in patterns:
            if pattern in ltext:
                c.append(country)
                break
    if "Somalia" in c: c.remove("Mali")
    if "Nigeria" in c: c.remove("Niger")
    if "Dominican Republic" in c and "Dominica" in c: c.remove("Dominica")
    if not c:
        c.append("Unknown")
    return c

    
COUNTRY_MAP = {
    'Afghanistan': ['afghanistan', 'afghan'],
    'Albania': ['albania'],
    'Algeria': ['algeria', 'argelia'],
    'Andorra': ['andorra'],
    'Angola': ['angola'],
    'Antigua and Barbuda': ['antigua and barbuda'],
    'Argentina': ['argentina'],
    'Armenia': ['armenia'],
    'Australia': ['australia'],
    'Austria': ['austria'],
    'Azerbaijan': ['azerbaijan'],
    'Bahamas': ['bahamas'],
    'Bahrain': ['bahrain'],
    'Bangladesh': ['bangladesh'],
    'Barbados': ['barbados'],
    'Belarus': ['belarus'],
    'Belgium': ['belgium'],
    'Belize': ['belize'],
    'Benin': ['benin'],
    'Bhutan': ['bhutan'],
    'Bolivia': ['bolivia'],
    'Bosnia and Herzegovina': ['bosnia and herzegovina'],
    'Botswana': ['botswana'],
    'Brazil': ['brazil'],
    'Brunei': ['brunei'],
    'Bulgaria': ['bulgaria'],
    'Burkina Faso': ['burkina faso'],
    'Burundi': ['burundi'],
    'Cabo Verde': ['cabo verde'],
    'Cambodia': ['cambodia'],
    'Cameroon': ['cameroon'],
    'Canada': ['canada'],
    'Central African Republic (CAR)': ['central african republic'],
    'Chad': ['chad'],
    'Chile': ['chile'],
    'China': ['china'],
    'Colombia': ['colombia'],
    'Comoros': ['comoros', 'comorian', 'comoran'],
    'Congo': ['congo'], # both democratic republic and republic
    'Costa Rica': ['costa rica'],
    "Cote d'Ivoire": ["cote d'ivoire", "ivory coast"],
    'Croatia': ['croatia'],
    'Cuba': ['cuba'],
    'Cyprus': ['cyprus'],
    'Czech Republic': ['czech republic'],
    'Denmark': ['denmark'],
    'Djibouti': ['djibouti'],
    'Dominica': ['dominica'],
    'Dominican Republic': ['dominican republic', 'domican republic'],
    'Ecuador': ['ecuador', 'ecuator'],
    'Egypt': ['egypt'],
    'El Salvador': ['salvador'],
    'Equatorial Guinea': ['equatorial guinea'],
    'Eritrea': ['eritrea'],
    'Estonia': ['estonia'],
    'Ethiopia': ['ethiopia'],
    'Fiji': ['fiji'],
    'Finland': ['finland'],
    'France': ['france'],
    'Gabon': ['gabon'],
    'Gambia': ['gambia'],
    'Georgia': ['georgia'],
    'Germany': ['germany'],
    'Ghana': ['ghana'],
    'Greece': ['greece'],
    'Grenada': ['grenada'],
    'Guatemala': ['guatemala'],
    'Guinea': ['guinea'],
    'Guinea-Bissau': ['guinea-bissau'],
    'Guyana': ['guyana'],
    'Haiti': ['haiti'],
    'Honduras': ['honduras', 'honduran'],
    'Hungary': ['hungary'],
    'Iceland': ['iceland'],
    'India': ['india'],
    'Indonesia': ['indonesia'],
    'Iran': ['iran'],
    'Iraq': ['iraq'],
    'Ireland': ['ireland'],
    'Israel': ['israel'],
    'Italy': ['italy'],
    'Jamaica': ['jamaica'],
    'Japan': ['japan'],
    'Jordan': ['jordan'],
    'Kazakhstan': ['kazakhstan'],
    'Kenya': ['kenya'],
    'Kiribati': ['kiribati'],
    'Kosovo': ['kosovo'],
    'Kuwait': ['kuwait'],
    'Kyrgyzstan': ['kyrgyzstan'],
    'Laos': ['laos'],
    'Latvia': ['latvia'],
    'Lebanon': ['lebanon', 'lebanese'],
    'Lesotho': ['lesotho'],
    'Liberia': ['liberia'],
    'Libya': ['libya'],
    'Liechtenstein': ['liechtenstein'],
    'Lithuania': ['lithuania'],
    'Luxembourg': ['luxembourg'],
    'Macedonia (FYROM)': ['macedonia', 'fyrom'],
    'Madagascar': ['madagascar', 'malagasy'],
    'Malawi': ['malawi'],
    'Malaysia': ['malaysia'],
    'Maldives': ['maldives'],
    'Mali': ['mali'],
    'Malta': ['malta'],
    'Marshall Islands': ['marshall islands'],
    'Mauritania': ['mauritania'],
    'Mauritius': ['mauritius'],
    'Mexico': ['mexico', 'mexican'],
    'Micronesia': ['micronesia'],
    'Moldova': ['moldova'],
    'Monaco': ['monaco'],
    'Mongolia': ['mongolia'],
    'Montenegro': ['montenegro'],
    'Morocco': ['morocco', 'moroccan'],
    'Mozambique': ['mozambique', 'mozambican'],
    'Myanmar (Burma)': ['myanmar', 'burma', 'rohingya'],
    'Namibia': ['namibia'],
    'Nauru': ['nauru'],
    'Nepal': ['nepal'],
    'Netherlands': ['netherlands'],
    'New Zealand': ['new zealand'],
    'Nicaragua': ['nicaragua'],
    'Niger': ['niger'],
    'Nigeria': ['nigeria', 'nigerian'],
    'North Korea': ['north korea'],
    'Norway': ['norway'],
    'Oman': ['oman'],
    'Pakistan': ['pakistan'],
    'Palau': ['palau'],
    'Palestine': ['palestine'],
    'Panama': ['panama'],
    'Papua New Guinea': ['papua new guinea'],
    'Paraguay': ['paraguay'],
    'Peru': ['peru'],
    'Philippines': ['philippines'],
    'Poland': ['poland'],
    'Portugal': ['portugal'],
    'Qatar': ['qatar'],
    'Romania': ['romania'],
    'Russia': ['russia'],
    'Rwanda': ['rwanda'],
    'Saint Kitts and Nevis': ['saint kitts and nevis'],
    'Saint Lucia': ['saint lucia'],
    'Saint Vincent and the Grenadines': ['saint vincent and the grenadines'],
    'Samoa': ['samoa'],
    'San Marino': ['san marino'],
    'Sao Tome and Principe': ['sao tome and principe'],
    'Saudi Arabia': ['saudi arabia'],
    'Senegal': ['senegal'],
    'Serbia': ['serbia'],
    'Seychelles': ['seychelles'],
    'Sierra Leone': ['sierra leone'],
    'Singapore': ['singapore'],
    'Slovakia': ['slovakia'],
    'Slovenia': ['slovenia'],
    'Solomon Islands': ['solomon islands'],
    'Somalia': ['somalia'],
    'South Africa': ['south africa'],
    'South Korea': ['south korea'],
    'South Sudan': ['south sudan'],
    'Spain': ['spain'],
    'Sri Lanka': ['sri lanka'],
    'Sudan': ['sudan'],
    'Suriname': ['suriname'],
    'Swaziland': ['swaziland'],
    'Sweden': ['sweden'],
    'Switzerland': ['switzerland'],
    'Syria': ['syria'],
    'Taiwan': ['taiwan'],
    'Tajikistan': ['tajikistan'],
    'Tanzania': ['tanzania'],
    'Thailand': ['thailand'],
    'Timor-Leste': ['timor-leste'],
    'Togo': ['togo'],
    'Tonga': ['tonga'],
    'Trinidad and Tobago': ['trinidad and tobago'],
    'Tunisia': ['tunisia'],
    'Turkey': ['turkey'],
    'Turkmenistan': ['turkmenistan'],
    'Tuvalu': ['tuvalu'],
    'Uganda': ['uganda'],
    'Ukraine': ['ukraine'],
    'United Arab Emirates (UAE)': ['united arab emirates (uae)'],
    'United Kingdom (UK)': ['united kingdom (uk)'],
    'United States of America (USA)': ['united states of america (usa)'],
    'Uruguay': ['uruguay'],
    'Uzbekistan': ['uzbekistan'],
    'Vanuatu': ['vanuatu'],
    'Vatican City (Holy See)': ['vatican city (holy see)'],
    'Venezuela': ['venezuela'],
    'Vietnam': ['vietnam'],
    'Yemen': ['yemen'],
    'Zambia': ['zambia'],
    'Zimbabwe': ['zimbabwe']
}
